/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'C562_GPIO_test_SW.debug_GCC+NUCLEO-C562RE' 
 * Target:  'debug_GCC+NUCLEO-C562RE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32c5xx.h"

/* STMicroelectronics::Device:Startup@2.0.0-beta.1 */
#define RTE_DEVICE_STARTUP_STM32C5XX    /* Device Startup for STM32C5 */


#endif /* RTE_COMPONENTS_H */
